# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'rom'
gem "rom-yaml"
gem "rom-repository"
# gem 'ruby-debug-ide'
# gem 'debase'
gem 'solargraph'
gem 'pry'
gem 'rom-sql'
gem 'sqlite3'
